insert into Modelo (nome_modelo, id_submodelo) values ('Savana 1500', 56);
insert into Modelo (nome_modelo, id_submodelo) values ('Corrado', 97);
insert into Modelo (nome_modelo, id_submodelo) values ('S-Class', 72);
insert into Modelo (nome_modelo, id_submodelo) values ('500E', 6);
insert into Modelo (nome_modelo, id_submodelo) values ('Taurus', 8);
insert into Modelo (nome_modelo, id_submodelo) values ('Tiguan', 12);
insert into Modelo (nome_modelo, id_submodelo) values ('Ram', 89);
insert into Modelo (nome_modelo, id_submodelo) values ('A5', 11);
insert into Modelo (nome_modelo, id_submodelo) values ('2500', 34);
insert into Modelo (nome_modelo, id_submodelo) values ('B-Series Plus', 5);
insert into Modelo (nome_modelo, id_submodelo) values ('Grand Cherokee', 47);
insert into Modelo (nome_modelo, id_submodelo) values ('Bronco II', 74);
insert into Modelo (nome_modelo, id_submodelo) values ('Sierra 2500', 39);
insert into Modelo (nome_modelo, id_submodelo) values ('del Sol', 55);
insert into Modelo (nome_modelo, id_submodelo) values ('6 Series', 46);
insert into Modelo (nome_modelo, id_submodelo) values ('IS', 17);
insert into Modelo (nome_modelo, id_submodelo) values ('Tacoma Xtra', 15);
insert into Modelo (nome_modelo, id_submodelo) values ('Avanti', 70);
insert into Modelo (nome_modelo, id_submodelo) values ('New Beetle', 71);
insert into Modelo (nome_modelo, id_submodelo) values ('C8', 8);
insert into Modelo (nome_modelo, id_submodelo) values ('Montero', 14);
insert into Modelo (nome_modelo, id_submodelo) values ('Dakota', 34);
insert into Modelo (nome_modelo, id_submodelo) values ('LTD Crown Victoria', 18);
insert into Modelo (nome_modelo, id_submodelo) values ('350Z Roadster', 29);
insert into Modelo (nome_modelo, id_submodelo) values ('Firebird', 54);
insert into Modelo (nome_modelo, id_submodelo) values ('Electra', 22);
insert into Modelo (nome_modelo, id_submodelo) values ('Bonneville', 22);
insert into Modelo (nome_modelo, id_submodelo) values ('3500 Club Coupe', 2);
insert into Modelo (nome_modelo, id_submodelo) values ('Galant', 6);
insert into Modelo (nome_modelo, id_submodelo) values ('Lumina', 82);
insert into Modelo (nome_modelo, id_submodelo) values ('Passat', 39);
insert into Modelo (nome_modelo, id_submodelo) values ('Lumina APV', 74);
insert into Modelo (nome_modelo, id_submodelo) values ('Discovery', 79);
insert into Modelo (nome_modelo, id_submodelo) values ('Camry', 55);
insert into Modelo (nome_modelo, id_submodelo) values ('Town Car', 71);
insert into Modelo (nome_modelo, id_submodelo) values ('Sierra 2500', 44);
insert into Modelo (nome_modelo, id_submodelo) values ('Cavalier', 70);
insert into Modelo (nome_modelo, id_submodelo) values ('Sierra 1500', 8);
insert into Modelo (nome_modelo, id_submodelo) values ('300C', 23);
insert into Modelo (nome_modelo, id_submodelo) values ('2500', 92);
insert into Modelo (nome_modelo, id_submodelo) values ('W201', 66);
insert into Modelo (nome_modelo, id_submodelo) values ('Yaris', 13);
insert into Modelo (nome_modelo, id_submodelo) values ('Rondo', 12);
insert into Modelo (nome_modelo, id_submodelo) values ('Pathfinder', 75);
insert into Modelo (nome_modelo, id_submodelo) values ('Yukon', 81);
insert into Modelo (nome_modelo, id_submodelo) values ('Yukon XL 1500', 63);
insert into Modelo (nome_modelo, id_submodelo) values ('Passat', 85);
insert into Modelo (nome_modelo, id_submodelo) values ('Thunderbird', 49);
insert into Modelo (nome_modelo, id_submodelo) values ('Metro', 55);
insert into Modelo (nome_modelo, id_submodelo) values ('Camaro', 13);
insert into Modelo (nome_modelo, id_submodelo) values ('Express 1500', 47);
insert into Modelo (nome_modelo, id_submodelo) values ('Sierra 3500', 21);
insert into Modelo (nome_modelo, id_submodelo) values ('CX-7', 54);
insert into Modelo (nome_modelo, id_submodelo) values ('Grand Marquis', 36);
insert into Modelo (nome_modelo, id_submodelo) values ('Camaro', 11);
insert into Modelo (nome_modelo, id_submodelo) values ('Monte Carlo', 55);
insert into Modelo (nome_modelo, id_submodelo) values ('Previa', 31);
insert into Modelo (nome_modelo, id_submodelo) values ('Biturbo', 47);
insert into Modelo (nome_modelo, id_submodelo) values ('Trooper', 84);
insert into Modelo (nome_modelo, id_submodelo) values ('Lancer', 81);
insert into Modelo (nome_modelo, id_submodelo) values ('Lynx', 19);
insert into Modelo (nome_modelo, id_submodelo) values ('Jetta', 17);
insert into Modelo (nome_modelo, id_submodelo) values ('RL', 60);
insert into Modelo (nome_modelo, id_submodelo) values ('Silverado 1500', 24);
insert into Modelo (nome_modelo, id_submodelo) values ('Lancer Evolution', 26);
insert into Modelo (nome_modelo, id_submodelo) values ('Avalon', 89);
insert into Modelo (nome_modelo, id_submodelo) values ('62', 47);
insert into Modelo (nome_modelo, id_submodelo) values ('S-Series', 62);
insert into Modelo (nome_modelo, id_submodelo) values ('Equinox', 75);
insert into Modelo (nome_modelo, id_submodelo) values ('Lumina', 84);
insert into Modelo (nome_modelo, id_submodelo) values ('Skylark', 83);
insert into Modelo (nome_modelo, id_submodelo) values ('Grand Am', 42);
insert into Modelo (nome_modelo, id_submodelo) values ('Land Cruiser', 9);
insert into Modelo (nome_modelo, id_submodelo) values ('E250', 72);
insert into Modelo (nome_modelo, id_submodelo) values ('Aspen', 36);
insert into Modelo (nome_modelo, id_submodelo) values ('S-Class', 38);
insert into Modelo (nome_modelo, id_submodelo) values ('R-Class', 23);
insert into Modelo (nome_modelo, id_submodelo) values ('Canyon', 31);
insert into Modelo (nome_modelo, id_submodelo) values ('Sienna', 94);
insert into Modelo (nome_modelo, id_submodelo) values ('Jetta', 3);
insert into Modelo (nome_modelo, id_submodelo) values ('Firebird', 22);
insert into Modelo (nome_modelo, id_submodelo) values ('Savana 2500', 82);
insert into Modelo (nome_modelo, id_submodelo) values ('Continental', 75);
insert into Modelo (nome_modelo, id_submodelo) values ('2e', 57);
insert into Modelo (nome_modelo, id_submodelo) values ('Cooper', 13);
insert into Modelo (nome_modelo, id_submodelo) values ('Optima', 4);
insert into Modelo (nome_modelo, id_submodelo) values ('Mohave/Borrego', 47);
insert into Modelo (nome_modelo, id_submodelo) values ('Impala', 45);
insert into Modelo (nome_modelo, id_submodelo) values ('Frontier', 12);
insert into Modelo (nome_modelo, id_submodelo) values ('Avalanche', 37);
insert into Modelo (nome_modelo, id_submodelo) values ('G-Class', 37);
insert into Modelo (nome_modelo, id_submodelo) values ('Electra', 48);
insert into Modelo (nome_modelo, id_submodelo) values ('Prelude', 64);
insert into Modelo (nome_modelo, id_submodelo) values ('Fortwo', 87);
insert into Modelo (nome_modelo, id_submodelo) values ('Diamante', 63);
insert into Modelo (nome_modelo, id_submodelo) values ('Camaro', 74);
insert into Modelo (nome_modelo, id_submodelo) values ('GTO', 93);
insert into Modelo (nome_modelo, id_submodelo) values ('Genesis Coupe', 88);
insert into Modelo (nome_modelo, id_submodelo) values ('iQ', 64);
insert into Modelo (nome_modelo, id_submodelo) values ('F430 Spider', 34);
